In [1]:
import pandas as pd
import geopandas as gpd

In [3]:
trash_data = gpd.read_file('./trash_hauler_report.csv')
trash_data

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1727970.41206786,686779.478088711
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1,1721259.36568104,685444.799565154
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20,1707026.75348931,659887.471571312
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2,1735691.77097349,685027.245922773
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20,1710185.77229504,664205.101065545
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013,RED RIVER,4502,32,1781137.26293528,632448.551143857
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206,METRO,9508,6,1749711.39882271,669201.601569129
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214,RED RIVER,1502,15,1770293.38813099,674936.303809043
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013,RED RIVER,4502,32,1785224.99799806,627146.400187231
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217,RED RIVER,2505,29,1781360.32310215,637742.006845765

In [17]:
# Finding unique values for the Request column 
pd.unique(trash_data['Request'])

array(['Trash - Backdoor', 'Trash - Curbside/Alley Missed Pickup',
       'Trash Collection Complaint', 'Damage to Property'], dtype=object)

In [35]:
backdoor = trash_data.loc[trash_data['Request'] == 'Trash - Backdoor']
backdoor.shape

(2629, 11)

In [36]:
cs_alley = trash_data.loc[trash_data['Request'] == 'Trash - Curbside/Alley Missed Pickup']
cs_alley.shape

(15028, 11)

In [15]:
complaint = trash_data.loc[trash_data['Request'] == 'Trash Collection Complaint']
#complaint

In [39]:
contains_miss = complaint['Description'].str.contains('miss', case = 'False', na ='False')
#contains_miss

C:\Users\EpicWork\AppData\Local\Temp\ipykernel_13892\3712832755.py:1: FutureWarning: Allowing a non-bool 'na' in obj.str.contains is deprecated and will raise in a future version.
  contains_miss = complaint['Description'].str.contains('miss', case = 'False', na ='False')

In [40]:
miss_complaint = complaint[contains_miss]
miss_complaint.shape

(453, 11)

In [43]:
miss_all = pd.concat([backdoor, cs_alley, miss_complaint], ignore_index = 'True')

In [47]:
miss_all['Short Address'] = miss_all['Incident Address'].str.split(',', n=1).str[0]
miss_all

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,Short Address
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1727970.41206786,686779.478088711,3817 Crouch Dr
1,25692,11/02/17,Trash - Backdoor,Backdoor/miss for last Friday. Does not unders...,3041 Fieldstone Dr,37013,RED RIVER,3504,29,1785677.15882833,633139.246264943,3041 Fieldstone Dr
2,25775,11/02/17,Trash - Backdoor,Missed trash pickup said has been picking up b...,4625 long br,37013,RED RIVER,4505,28,1770350.41605229,634143.871818357,4625 long br
3,25802,11/02/17,Trash - Backdoor,Missed.,4828 Cimarron Way,37013,RED RIVER,3404,30,1766186.56409375,629785.602877192,4828 Cimarron Way
4,25858,11/03/17,Trash - Backdoor,Missed- she said her grandson was over yesterd...,2005 Lebanon Pike,37210,RED RIVER,1504,15,1760561.7630735,665276.001224629,2005 Lebanon Pike
...,...,...,...,...,...,...,...,...,...,...,...,...
18105,266466,10/31/19,Trash Collection Complaint,"Paid/Backdoor-Trash missed last Thursday, does...","809 Winthorne Ct, Nashville, TN 37217, United ...",37217,RED RIVER,1402,16,1759043.58424902,651549.019214337,809 Winthorne Ct
18106,266628,10/31/19,Trash Collection Complaint,Disabled caller stated she is keep getting mis...,"1719 Windover Dr, Nashville, TN 37218, United ...",37218,RED RIVER,4202,2,1718308.69339541,680762.907491275,1719 Windover Dr
18107,266708,11/01/19,Trash Collection Complaint,Caller stated her trash has been missed for 2 ...,"4305 Granny White Pike, Nashville, TN 37204, U...",37204,RED RIVER,3302,25,1731857.80036635,644223.201524295,4305 Granny White Pike
18108,266710,11/01/19,Trash Collection Complaint,"Trash/has been missed for weeks in a row, curb...","3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013,RED RIVER,4502,32,1785224.99799806,627146.400187231,3325 Murfreesboro Pike
18109,266732,11/01/19,Trash Collection Complaint,Caller stated her trash misses her trash all t...,"2114 Vine Hill Rd, Nashville, TN 37204, United...",37204,METRO,9406,17,1741197.38231891,655129.23648106,2114 Vine Hill Rd

In [64]:
miss_count_by_address = miss_all['Short Address'].value_counts().reset_index(name='Missed Pickups')
#miss_count_by_address = miss_count_by_address.to_frame()
miss_count_by_address

                  Short Address  Missed Pickups
0       110 George L Davis Blvd              25
1        12546 Old Hickory Blvd              21
2      5135 Hickory Hollow Pkwy              20
3               802 Crescent Rd              19
4          1816 Jo Johnston Ave              18
...                         ...             ...
12207           6205 del sol dr               1
12208           2216 sadler ave               1
12209            2339 Revere Pl               1
12210        3808 ASHEFORD TRCE               1
12211         2114 Vine Hill Rd               1

[12212 rows x 2 columns]

In [67]:
frequently_missed = miss_count_by_address.loc[miss_count_by_address['Missed Pickups'] > 1]
frequently_missed

                 Short Address  Missed Pickups
0      110 George L Davis Blvd              25
1       12546 Old Hickory Blvd              21
2     5135 Hickory Hollow Pkwy              20
3              802 Crescent Rd              19
4         1816 Jo Johnston Ave              18
...                        ...             ...
3119            22 Wynfield Ct               2
3120               552 Judd Dr               2
3121               342 LYNN DR               2
3122        1404 Wedgewood Ave               2
3123         1007 Draughon Ave               2

[3124 rows x 2 columns]